### ISSUE TITLE
Ordering of ACL rules

### ISSUE THREAD

**Issue by rdanyliw** [dotswg/dots-data-channel#1]
During slide 14 of [Jon Shallow's implementation report](https://datatracker.ietf.org/meeting/interim-2017-dots-03/materials/slides-interim-2017-dots-03-sessa-ncc-group-implementation-experience/) at the the October 2017 interim, the [minutes](https://datatracker.ietf.org/meeting/interim-2017-dots-03/materials/minutes-interim-2017-dots-03-201710021000/) captured a need for further specificity describing what meaning ACLs list ordering has. 

--[snip]--
Comment: (Roland Dobbins): Ordering of ACL rules will have to be done client or server side.
A: (Jon Shallow): The protocol needs more specificity to allow standardized handling of the ACLs
A: (Tiru Reddy): We need to approach the NetMod draft authors to discuss this further
A: (Roman Danyliw): Who can make that link?  Is help from the chairs required?
                  : Jon Shallow volunteers.
--[snip]--

**Comment by tireddy2** [comment]
https://tools.ietf.org/html/draft-ietf-dots-data-channel-08 extends the ACL YANG module to support ordering of ACLs from a DOTS client.
